# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: Restore cache
      id: yocto-cache-restore
      uses: actions/cache/restore@v4
      with:
        path: vendor
        key: yocto-cache-latest

    - name: Restore broken cache
      if: steps.yocto-cache-restore.outputs.cache-hit != 'true'
      id: yocto-broken-cache-restore
      uses: actions/cache/restore@v4
      with:
        path: vendor
        key: yocto-broken-cache-latest
    
    - name: Install build prerequisites
      if: steps.yocto-cache-restore.outputs.cache-hit != 'true'
      run: |
        go mod vendor

    - name: Build
      id: build
      run: |
        go get "github.com/labstack/echo/v4" 
        go build -v app/cmd/app/main.go

    - name: Install build prerequisites
      if: steps.build.outcome == 'failure'
      run: |
        go mod vendor   
      
    - name: Save cache
      id: yocto-cache-save
      uses: actions/cache/save@v4
      if: steps.build.outcome != 'success'
      with:
        path: vendor
        key: yocto-cache-latest

    - name: Save Broken cache
      if: steps.build.outcome == 'failure'
      id: yocto-broken-cache-save
      uses: actions/cache/save@v4
      with:
        path: vendor
        key: yocto-broken-cache-latest

